language: r
r:
  - oldrel
  - release
  - devel

cache:
  - packages
  - pip

addons:
  apt:
    packages:
      - python3-pip

before_install:
  - pip3 install --user -U pip3
  - pip3 install --user setuptools numpy

after_success:
  - Rscript -e 'covr::codecov()'
