language: R
sudo: true
# r:
#   - oldrel
#   - release
#   - devel

cache:
  - packages
  - pip

addons:
  apt:
    packages:
      - python3-pip

before_install:
  - sudo pip install --upgrade pip
  - sudo apt install python3-pip
  - sudo apt-get install python3-setuptools
  - pip3 install --user numpy

after_success:
  - Rscript -e 'covr::codecov()'
