language: r
dist: focal
r:
#  - oldrel
  - release
#  - devel

# cache:
#   - packages
#   - pip

# addons:
#   apt:
#     packages:
#       - r-cran-reticulate
#       # - python3-pip
#       # - python3-setuptools

before_install:
  - env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.6

after_success:
  - Rscript -e 'covr::codecov()'
