language: r
sudo: true
# r:
#   - oldrel
#   - release
#   - devel

cache:
  - packages
  - pip

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools

# before_install:
#   - sudo pip install --upgrade pip

after_success:
  - Rscript -e 'covr::codecov()'
