language: r
dist: bionic
r:
  - oldrel
  - release
  - devel

cache:
  - packages
  - pip

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools

before_install:
  - pip3 install --local networkx pandas

after_success:
  - Rscript -e 'covr::codecov()'
